### ISSUE TITLE
title is not shown 

### ISSUE THREAD

**Issue by wiemann** [tutorialzine/touchTouch#6]
Even though the title-tag for the link is used, the plugin doesn't show the title when displaying the image. It should make use of the title tag. In the examples the title tag is also filled, but unfortunately it doesn't trigger any action in the display.

**Comment by leecody** [comment]
I modified the plugin to add this for my own implementation, it's not too difficult.

You'd need to add in the container to hold the title when you add in all the other elements:

``` javascript
        imageTitle = $('<div id="imageTitle"></div>'),
```

Then just update it on slide change. You can add this into the offsetSlider() function.

``` javascript
            var newTitle = items.eq(index).attr("title");
            imageTitle.html(newTitle);
```

...aaaand style it in the css:

``` css
#imageTitle {
    color: #FFFFFF;
    width: 100%;
    text-align: center;

    bottom: 8%;
    left: 0;
}
```

**Comment by helixconcepts** [comment]
Can you please explain this in greater detail for folks like myself who don't have much experience with javascript. Thanks

**Comment by moiseevigor** [comment]
I've just committed the leecody proposal, check it out https://github.com/moiseevigor/touchTouch/commit/1f3667a03bddb0ae32197577a196d21b6e5517e3
Hope it helps!

**Comment by martinaglv** [comment]
I think you are missing a <code>position:absolute;</code> in your #imageTitle block.

Also, for bonus points, here is a quick way to add a dark background to the text, without changes to the markup or js:

``` css
#imageTitle::first-line {
    background-color: rgba(0, 0, 0, 0.8);
}
```

I am not sure which mobile browsers support it, but it works nicely in Chrome and it won't hurt in any case.
